implement support of context path
artipie/npm-proxy-adapter pull request #21
Opened 2020-04-28 12:12 UTC by brastak

For #15

2020-04-28 13:00 UTC, 0crat commented
This pull request [#21](https://github.com/artipie/npm-proxy-adapter/issues/21) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5245388d-9972-41bd-8cee-65127a6ae0f3); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/2449084e-4daa-4050-956c-7e42ba902315, version: 0.53.13, hash: ${buildNumber} -->

2020-04-28 19:35 UTC, Vatavuk requested changes
@brastak comments below

2020-04-28 19:35 UTC, Vatavuk commented on src/main/java/com/artipie/npm/proxy/http/AssetPath.java
> + * Asset path helper.
@brastak please expand the description.

2020-04-28 19:35 UTC, Vatavuk commented on src/main/java/com/artipie/npm/proxy/http/NpmPath.java
> +    public String value(final String abspath) {
@brastak make this method final

2020-04-28 19:35 UTC, Vatavuk commented on src/main/java/com/artipie/npm/proxy/http/NpmPath.java
> +    public String prefix() {
@brastak make this method final

2020-04-28 19:35 UTC, Vatavuk commented on src/main/java/com/artipie/npm/proxy/http/PackagePath.java
> + * Package path helper.
@brastak please expand the description

2020-04-29 07:46 UTC, brastak commented
@Vatavuk please see update

2020-04-29 08:51 UTC, Vatavuk approved these changes
@brastak thx
@g4s8 good to merge

2020-04-29 14:52 UTC, g4s8 approved these changes

2020-04-29 14:53 UTC, merged

2020-04-29 15:10 UTC, 0crat commented
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

<!-- https://www.0crat.com/footprint/CT2E6TK9B/ba4049c8-f0c6-47d8-9bed-ec8655155733, version: 0.53.13, hash: ${buildNumber} -->

2020-04-29 15:10 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/CT2E6TK9B/664112c9-8cd3-447a-9dc9-57ed1c41328f, version: 0.53.13, hash: ${buildNumber} -->

2020-04-29 15:17 UTC, sereshqua commented
@0crat quality good