Feature/fix codecoverage for npm proxy
artipie/npm-proxy-adapter pull request #31
Opened 2020-05-26 15:34 UTC by brastak

For #30

2020-05-27 02:28 UTC, 0crat commented
This pull request [#31](https://github.com/artipie/npm-proxy-adapter/issues/31) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5267e3a9-193c-46ef-a483-20114c80996a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/b088e4b4-d373-488f-90dc-c5eb84cccc04, version: 0.53.14, hash: ${buildNumber} -->

2020-05-27 08:40 UTC, carlosmiranda requested changes
@brastak just one comment

2020-05-27 08:40 UTC, carlosmiranda commented on src/test/java/com/artipie/npm/proxy/json/CachedContentTest.java
> +        final String ref = json.read("$.versions.['1.0.0'].dist.tarball", String.class);
@brastak let's inline this variable.

2020-05-27 10:39 UTC, brastak commented on src/test/java/com/artipie/npm/proxy/json/CachedContentTest.java
> +        final String ref = json.read("$.versions.['1.0.0'].dist.tarball", String.class);
@carlosmiranda done

2020-05-27 10:40 UTC, brastak commented
@carlosmiranda please, see update

2020-05-28 14:53 UTC, brastak commented
@carlosmiranda ping

2020-05-29 01:45 UTC, carlosmiranda approved these changes
@brastak thanks. @g4s8 this looks good from my end

2020-05-29 08:52 UTC, g4s8 approved these changes

2020-05-29 08:52 UTC, merged

2020-05-29 09:09 UTC, 0crat commented
Job `gh:artipie/npm-proxy-adapter#31` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/9088f50a-924b-498c-ac60-91b547a61c8c, version: 0.53.15, hash: ${buildNumber} -->